---
kind: BuildingKind
spec:
  category: custom
  name: Base
  description: Puts a base on the map to conquer an area
  model: 99-99
  color: 5
  contract:
    file: ./Base.sol
  materials:
    - name: Red Goo
      quantity: 10
    - name: Green Goo
      quantity: 10
    - name: Blue Goo
      quantity: 10
