---
kind: BuildingKind
spec:
  category: custom
  name: TW Base
  description: Puts a base on the map to conquer an area
  model: 01-08
  color: 5
  contract:
    file: ./Base.sol
  plugin:
    file: ./Base-deploy.js
  materials:
    - name: TW Hammer
      quantity: 1
